CREATE PROCEDURE LOGIN_
	@EMAIL AS VARCHAR(250)= NULL,
	@PASSWORD AS VARCHAR(250)
AS
DECLARE @USERID AS INT
DECLARE @LOGINTYPE AS VARCHAR(100)
IF @EMAIL IS NOT NULL
	BEGIN
	SELECT @USERID =ID FROM Users_ WHERE Email = @EMAIL AND Password_ = @PASSWORD
	IF @USERID > 0
		BEGIN
			SET @LOGINTYPE ='GÝRÝÞ BAÞARILI'
			INSERT INTO UserLoginLog(UserId,LoginType,IpAddress,DATE_) VALUES
			(@USERID,@LOGINTYPE,CONVERT(VARCHAR,CONNECTIONPROPERTY('client_net_address')),GETDATE())
		END
	ELSE
		BEGIN
			SET @LOGINTYPE ='GÝRÝÞ BAÞARISIZ'
			INSERT INTO UserLoginLog(UserId,LoginType,IpAddress,DATE_) VALUES
			(@USERID,@LOGINTYPE,CONVERT(VARCHAR,CONNECTIONPROPERTY('client_net_address')),GETDATE())
		END
	END



 -- EXEC LOGIN_ @EMAIL ='ahmet@ahmet.com' ,@PASSWORD ='ahmet1'