CREATE PROC WORKER_INOUT
-- ÖNCELÝKLE PROCEDURE PARAMETRELERÝNÝ TANIMLAMALIYIZ.
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATE,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS 
BEGIN

-- GEREKLÝ DEÐÝÞKENLERÝ TANIMLADIK.
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT
DECLARE @LASTIO AS VARCHAR
-- ÇALIÞANLAR TABLOSUNDA EÞLEÞEN KAYDIN DEÐERLERÝNÝ DEÐÝÞKENLERE ATADIK.
SELECT @WORKERNAME = WorkerName, @WORKERID = ID FROM Workers WHERE WorkerBarcode = @WORKERBARCODE

-- HERHANGÝ BÝR KAYIT EÞLEÞMEZSE ÇALIÞACAK KOD BLOÐU
IF @WORKERID IS NULL
	BEGIN
		RAISERROR ('Kullanýcý bulunamadý',16,1)
		RETURN
	END

-- ÇALIÞANIN EN SON YAPMIÞ OLDUÐU GÝRÝÞ VEYA ÇIKIÞ ÝÞLEMÝNÝ TESPÝT ETTÝK.
SELECT TOP 1 @LASTIO = IOTYPE FROM WorkerLog WHERE WORKERID = @WORKERID AND DATE_ = CONVERT(date,GETDATE())
ORDER BY DATE_ DESC

-- AYNI ÝÞLEMÝ TEKRARLAMASINA KARÞI ÝÞLEM TÝPÝ KONTROLÜ SAÐLADIK.
IF @LASTIO = @IOTYPE
	BEGIN
		IF @IOTYPE = 'G'
		BEGIN
			RAISERROR('Öncelikle çýkýþ yapmalýsýnýz. Tekrar giriþ yapamazsýnýz',16,1)
		END
		IF @IOTYPE = 'C'
		BEGIN
			RAISERROR('Öncelikle giriþ yapmalýsýnýz. Tekrar çýkýþ yapamazsýnýz',16,1)
		END

	END
-- ÇALIÞANIN GÝRÝÞ VE ÇIKIÞ ÝÞLEMLERÝNÝ LOG TABLOSUNA KAYIT ETTÝK.
 INSERT INTO WorkerLog (WORKERID,DATE_,IOTYPE,GATEID)
 VALUES (@WORKERID,@DATE,@IOTYPE,@GATEID)
END