CREATE VIEW ITEM_SALES
AS
SELECT I.ITEMCODE, I.ITEMNAME,
MIN(OD.UNITPRICE) AS MINPRICE,
MAX(OD.UNITPRICE) AS MAXPRICE,
AVG(OD.UNITPRICE) AS AVGPRICE,
SUM(OD.LINETOTAL) AS TOTALPRICE,
SUM(OD.AMOUNT) AS SUMAMOUNT

FROM ORDERDETAILS OD

INNER JOIN ORDERS O ON OD.ORDERID = O.ID
INNER JOIN ITEMS I ON I.ID = OD.ITEMID

GROUP BY I.ITEMCODE,I.ITEMNAME


SELECT * FROM ITEM_SALES ORDER BY ITEMCODE